#!/bin/sh

set -eu

readonly f="${1}"
shift

pkg="$(awk '/Package/ {print $NF}' "${f}" | head -n1)"

category="$(qatom --format '%{CATEGORY}' "${pkg}")"
pn="$(qatom --format '%{PN}' "${pkg}")"
pv="$(qatom --format '%{PV}' "${pkg}")"

pr="$(qatom --format '%{PR}' "${pkg}")"
[ "${pr}" = 'r0' ] && pr=''
[ ! -z "${pr}" ] && pr="-${pr}"

repository_name="$(awk '/Repository/ {print $NF}' "${f}" | head -n1)"
repository="$(portageq get_repo_path / "${repository_name}")"

ebuild "${repository}/${category}/${pn}/${pn}-${pv}${pr}.ebuild" "${@}"
