#!/bin/sh -eu

get_matcher() {
	if [ $# -eq 0 ]
	then
		return
	fi

	local out="/$1"
	shift
	for arg
	do
		out="$out|$arg"
	done
	echo "$out/"
}

[ $# -eq 1 ] && if [ \( "$1" = -h -o "$1" = --help \) ]
then
	echo "$0 [pkg-to-include]..."
	exit 0
fi

readonly MATCH="$(get_matcher "$@")"

while pgrep --list-full emerge | grep -q python
do
	qlop -rMF '%{CATEGORY}/%{PF}' | tac |
		awk "$MATCH "'{print gensub("\\.\\.\\.$", "", 1, $3)}' |
		while read pkg
	do
		pgrep --list-full --full /ebuild.sh | grep -qF "${pkg}" || continue
		echo ">> ${pkg}"
		tail --follow=name -n0 "/var/tmp/portage/${pkg}/temp/build.log" 2>/dev/null || :
	done
done
