#!/bin/sh

set -eu

while pgrep --list-full emerge | grep -q python
do

	qlop -c | awk '/^ \* / {print $2}' | head -n1 | while read pkg
	do
		echo ">> ${pkg}"
		tailf -n0 "/var/tmp/portage/${pkg}/temp/build.log"
	done
done
