#!/usr/bin/env bash

set -eu
set -o pipefail

syntax () {
	cat <<- EOF
${0} [-h|--help]
${0} [-a|--ask] [arguments-to-optimize-world...]

${0} will do nearly all common administrative task needed under a Gentoo system.

I will not sync the portage tree for you, because you may want to rerun multiple
times ${0} and do not want to flood the sync servers.

	-a
	--ask	add --ask to some commands
	EOF

	exit 0
}

asking=false
[ ${#} -eq 1 ] && [ "${1}" = '-h' -o "${1}" = '--help' ] && syntax "${@}"
[ ${#} -ge 1 ] && [ "${1}" = '-a' -o "${1}" = '--ask' ] && asking=true && shift

tmpfile="$(mktemp)"
running_cmd=''
failed_cmd=''

trap on_exit EXIT INT

on_exit() {
	local status=${?}

	if [ -n "${running_cmd}" ]
	then
		failed_cmd+="
		${running_cmd}"
		running_cmd=''
	fi

	if [ -n "${failed_cmd}" ]
	then
		# most case is ^C
		[ ${status} -ne 0 ] && echo

		echo '>> some commands have failed'
		echo "${failed_cmd}" | tail -n +2 | while read l
		do
			echo ">>   - ${l}"
		done

		# reset for next run by exit
		failed_cmd=''
	fi

	rm -f "${tmpfile}"

	exit ${status}
}

unbuffer() {
	stdbuf -i 0 -o 0 "${@}"
}

msg() {
	echo '>> check messages and press enter' | tr -d '\n'
	read null
}

run() {
	echo ">> ${@}"

	local regex=''
	if [ "${1}" = emerge ] || [ "${1}" = smart-live-rebuild ]
	then
		regex='Messages'
	fi

	set +e
	running_cmd="${@}"
	unbuffer "${@}" 2>&1 | tee "${tmpfile}"
	if [ ${?} -ne 0 ]
	then
		failed_cmd+="
		${running_cmd}"
		running_cmd=''
	fi
	set -e

	if [ -n "${regex}" ] && grep -q "${regex}" "${tmpfile}"
	then
		msg
	fi
}

try_run() {
	if type "${1}" >/dev/null 2>&1
	then
		run "${@}"
	fi
}

paludis_routine() {
	set +u
	. /etc/paludis/bashrc
	set -u

	run	cave resolve --complete --continue-on-failure if-satisfied --execute world "${@}"
	run	cave fix-linkage
	run	cave manage-search-index --create "${SEARCH_INDEX:-/var/paludis/index}"
	run	cave purge --execute
	run	rm -rf /var/tmp/paludis/*
}

portage_routine() {
	local emerge_opts='--color=y' eclean_kernel_opts=
	if $asking
	then
		emerge_opts+=' --ask'
		eclean_kernel_opts='--ask'
	fi

	run	emerge --update --newuse --deep --with-bdeps=y --complete-graph=y @world "${@}" ${emerge_opts}
	try_run	smart-live-rebuild -- ${emerge_opts}
	run	emerge @preserved-rebuild ${emerge_opts}
	run	emerge --depclean ${emerge_opts}
	try_run	eclean -d distfiles
	try_run eclean-kernel --all ${eclean_kernel_opts}
	try_run	glsa-check -t all
	run	emaint --fix all
	run	rm -rf /var/tmp/portage/*
}

case ${PACKAGE_MANAGER:-} in
	paludis)
		paludis_routine "${@}"
		;;
	portage)
		portage_routine "${@}"
		;;
	*)
		echo '>> no $PACKAGE_MANAGER set, defaulting to portage.'
		portage_routine "${@}"
		;;
esac

try_run	polipo -x
try_run	updatedb
try_run	rlpkg --all --reset
try_run	revdep-pax -f
