#!/usr/bin/env bash

set -eu
set -o pipefail

syntax () {
	cat <<- EOF
${0} [-a] [arguments-to-optimize-world...]

${0} will do nearly all common administrative task needed under a Gentoo system.

I will not sync the portage tree for you, because you may want to rerun multiple
times ${0} and do not want to flood the sync servers.

	-a	add --ask to emerge opts
	EOF

	exit 0
}

asking=false
if [ ${#} -gt 0 ]
then
	if [ \( "${1}" = '-h' -o "${1}" = '--help' \) ]
	then
		syntax "${@}"
	fi

	[ "${1}" = '-a' ] && asking=true && shift
fi

tmpfile="$(mktemp)"
running_cmd=''
failed_cmd=''

trap on_exit EXIT INT

on_exit() {
	local status=${?}

	if [ -n "${running_cmd}" ]
	then
		failed_cmd+="
		${running_cmd}"
		running_cmd=''
	fi

	if [ -n "${failed_cmd}" ]
	then
		# most case is ^C
		[ ${status} -ne 0 ] && echo

		echo '>> some commands have failed'
		echo "${failed_cmd}" | tail -n +2 | while read l
		do
			echo ">>   - ${l}"
		done

		# reset for next run by exit
		failed_cmd=''
	fi

	rm -f "${tmpfile}"

	exit ${status}
}

unbuffer() {
	stdbuf -i 0 -o 0 "${@}"
}

msg() {
	echo '>> check messages and press enter' | tr -d '\n'
	read null
}

run() {
	echo ">> ${@}"

	local regex=''
	local opts=''
	case "${1}" in
		emerge)
			regex='Messages'
			opts='--color=y';;
		smart-live-rebuild)
			regex='Messages'
			opts='-- --color=y';;
	esac

	set +e
	running_cmd="${@}"
	unbuffer "${@}" ${opts} 2>&1 | tee "${tmpfile}"
	if [ ${?} -ne 0 ]
	then
		failed_cmd+="
		${running_cmd}"
		running_cmd=''
	fi
	set -e

	if [ -n "${regex}" ] && grep -q "${regex}" "${tmpfile}"
	then
		msg
	fi
}

try_run() {
	if type "${1}" >/dev/null 2>&1
	then
		run "${@}"
	fi
}

paludis_routine() {
	set +u
	. /etc/paludis/bashrc
	set -u

	run	cave resolve --complete --continue-on-failure if-satisfied --execute world "${@}"
	run	cave fix-linkage
	run	cave manage-search-index --create "${SEARCH_INDEX:-/var/paludis/index}"
	run	cave purge --execute
	run	rm -rf /var/tmp/paludis/*
}

portage_routine() {
	if $asking
	then
		export EMERGE_DEFAULT_OPTS='--ask'
	fi

	run	emerge --update --newuse --deep --with-bdeps=y --complete-graph=y @world "${@}"
	try_run	smart-live-rebuild
	run	emerge @preserved-rebuild
	run	emerge --depclean
	try_run	eclean -d distfiles
	try_run eclean-kernel -A
	try_run	glsa-check -t all
	run	emaint --fix all
	run	rm -rf /var/tmp/portage
}

case ${PACKAGE_MANAGER:-} in
	paludis)
		paludis_routine "${@}"
		;;
	portage)
		portage_routine "${@}"
		;;
	*)
		echo '>> no $PACKAGE_MANAGER set, defaulting to portage.'
		portage_routine "${@}"
		;;
esac

try_run	polipo -x
try_run	updatedb
try_run	rlpkg --all --reset
try_run	revdep-pax -f
