#!/usr/bin/env python3

from parse_atom import *

valid_line = '=app-portage/gentools-9999:0/0::tharvik'

def syntax():

    print("""
Parse an atom on stdin and output the wanted parts.

One can select:
    """.strip())

    for opt in atom(valid_line).__dict__.keys():
            print(' - ' + opt)
    print()
    print("""
If you have a fully qualified atom, you need to add '=' in front to avoid having
it taken by the package name parser

For example, to get 'gentools', one can do
  echo '{}' | parse_atom package
    """.strip().format(valid_line))

    sys.exit(1)

def main():
    if len(sys.argv) is 1 or len(set(sys.argv[1:]) - atom(valid_line).__dict__.keys()) > 0:
        syntax()

    for l in sys.stdin:
        l = l.strip()

        a = atom(l)
        ret = a.to_str(sys.argv[1:])
        if ret is not '':
            print(ret)

main()
